DECLARE		@CMD				VARCHAR(1000); 
DECLARE		@PATCH				VARCHAR (MAX);
DECLARE		@NOMBRE_ARCHIVO		VARCHAR (MAX);
DECLARE		@NAME_DB			VARCHAR(100);
DECLARE		@BD_ID				VARCHAR(5);

	
SET @PATCH ='' 		---declare patch
SET @NAME_FILE = ''--	ex. 'test.txt'
 
		
DECLARE EXPORT CURSOR FOR

SELECT name,CONVERT(VARCHAR,database_id)  FROM master.sys.databases --- ex. query

OPEN EXPORT
FETCH NEXT FROM EXPORT
INTO @NAME_DB, @DB_ID
WHILE  @@FETCH_STATUS = 0
BEGIN
SET @Cmd ='echo ' +  @NAME_DB+';'+@DB_ID + ' >> '+@PATCH+''+@NAME_FILE+''
EXECUTE xp_CmdShell  @Cmd
FETCH NEXT FROM EXPORT
INTO @NAME_DB, @DB_ID
END
CLOSE EXPORT 
DEALLOCATE EXPORT

